### ISSUE TITLE
Localhost refused to connect

### ISSUE THREAD

**Issue by AlexGr3** [SickChill/SickChill#5162]
Hello everyone,
Sickchill was working just fine until yesterday when I couldnt access the web page. Is there any way to fix that? Thanks a lot. #

**Comment by WebSpider** [comment]
We will need a bit more information to help you troubleshoot what's going on with your install.

- Have you tried turning it off and back on again?
- On what system are you running SickChill (hardware/OS)
- Can you find your logfiles and see what they are saying?

**Comment by AlexGr3** [comment]
How can I turn it on and off if I cant access the webui? I am running it on windows 10 currently and the only logfile I can see is the following. 
[sickchill.log](https://github.com/SickChill/SickChill/files/2542759/sickchill.log)

**Comment by mijollo** [comment]
Hi everybody, it seems I have a similar Problem, after the Update from I can't connect to sickchill. Running it on qnap with qts 4.3.4, which was working fine untill now. Restartet the App and even the NAS. Thanks in advance for any help.
[log.txt](https://github.com/SickChill/SickChill/files/2543900/log.txt)

**Comment by Plokip8** [comment]
Hello Everyone,

looks like I have the same problem: "ERR_CONNECTION_REFUSED". Extra info:
- Using PC running Windows 10 1803 and latest version of Chrome (but also used Firefox and IE to check)
- I updated from Sickrage to SickChill on 21st of Oct. Using instructions from [here](https://github.com/SickChill/SickChill/issues/5022).
- I noticed the problem today, but checking sickchill.log the latest update is from yesterday (30 oct, 15:52 CET) stating: INFO     EVENT-QUEUE :: Shutting down Tornado
2018-10-30 15:52:09 INFO     EVENT-QUEUE :: Restarting SickChill with.... (Full log below)
- Checking Windows taskmanager shows python.exe using around 50% of my CPU capacity. (Quadcore CPU)
- Checking services.msc shows the sickrage service is running. 
- Rebooting SickChill and/or PC didn't help. Python.exe comes back up and starts taking around 50% CPU again. Tried multiple times with same result.

Thanks in advance and I hope this extra info helps solving this issue.
[sickchill.log](https://github.com/SickChill/SickChill/files/2544222/sickchill.log)

**Comment by soknet** [comment]
I have solved it following the instructions at: ["How to fix things"] https://github.com/SickChill/SickChill/issues/5022#issuecomment-428463717

With the actual repository https://github.com/SickChill/SickChill.git

And finally doing a: git pull

**Comment by AlexGr3** [comment]
Thats not gonna fix it for me since I installed SickChill from scratch so the issue isnt the fact that echelon messed up sickrage.

**Comment by AlexGr3** [comment]
Cheerios! I fixed it by backing up everything and doing a quick reinstall!

**Comment by Plokip8** [comment]
Thanks miigotu, it worked!

**Comment by zahiermajiet** [comment]
Hi,

I am having the same problem "localhost refused to connect"

- I am using windows 10 with google chrome
- Port 8081
- I did a reinstall but the issue persists
- Did a start & stop also not helping
- Logs
- 2020-12-21 16:47:02 INFO :: CHECKVERSION :: Request failed: HTTPSConnectionPool(host='sickchill.github.io', port=443): Max retries exceeded with url: /sickchill-news/news.md (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x000002CFD1A2C610>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed')) (<class 'str'>)
2020-12-21 17:08:37 INFO :: MAIN :: 390130: Unable to find IMDb show info in the database
2020-12-21 17:08:37 INFO :: MAIN :: Starting SickChill [master] using 'C:\SickChill\Data\config.ini'
2020-12-21 17:08:37 INFO :: MAIN :: Forcing web server to port 8081
2020-12-21 17:08:37 INFO :: WEBSERVER :: Starting SickChill on http://0.0.0.0:8081/
2020-12-21 17:08:37 INFO :: CHECKVERSION :: Checking for updates using GIT
