### ISSUE TITLE
Error in french translation for anime edition

### ISSUE THREAD

**Issue by cswormy** [SickChill/SickChill#5218]
In page : http://localhost:8081/home/editShow?show=xxxxx
For english you have : 
"Anime   [ ]  check if the show is Anime and episodes are released as Show.265 rather than Show.S02E03"
In french : 
"Animé   [ ]  vérifier si les séries de type animé apparaissent comme **Show.03.02.2010** plutôt que Show.S02E03"

It is a copy/paste error I think with the previous line. 

The correct sentence is : 
"Animé   [ ]  vérifier si les séries de type animé apparaissent comme **Show.265** plutôt que Show.S02E03"

**Comment by miigotu** [comment]
Should be fixed in the next update.
For future reference: https://crowdin.com/translate/sickchill/13/enus-fr

**Comment by cswormy** [comment]
@miigotu I have translated all missing text I understand on crowdin

**Comment by lobofoots** [comment]
@miigotu 
Sorry, but this mistranslation is still present in current version.

Animé vérifier si les séries de type animé apparaissent comme Show.03.02.2010 plutôt que Show.S02E03
