### ISSUE TITLE
Unable to add new shows due to TVDB SSL issue?

### ISSUE THREAD

**Issue by shropshirehobbit** [SickChill/SickChill#5756]
Hi been trying to add a show for a couple of days now since i picked up the latest commits (hadn't done this in while).  It seems it doesn't like the tvdb api (i've seen there's lots of noise about this on t'interweb forums). However don't seem to see anyone else having my SSL issue?

Branch/Commit: master
OS: install on raspberry pi 3 armv7l with raspbian (kernel 4.19.66-v7+)
Browser: Safari - was browsing my install from a remote machine. Also tried chrome 
What you did: tried to add a new show from IMDB listings.  Have also tried to add manually and via search and from trakt list and get the same errors.  Have also tried under the develop branch as well.
What happened: it failed to add the show with SSL errors (Seee below)
What you expected: to add the show!
Logs:

```
2019-12-07 17:38:08 DEBUG    ThreadPoolExecutor-0_1 :: Searching for Show with searchterm(s): ['mandalorian'] on Indexer: theTVDB
2019-12-07 17:39:04 INFO     ThreadPoolExecutor-0_0 :: theTVDB: {u'useZip': True, u'apikey': u'F9C450E78D99172E', u'cache': u'/opt/sickrage/cache/indexers/theTVDB', u'language': u'en'}
2019-12-07 17:39:05 WARNING  ThreadPoolExecutor-0_0 :: Show id 360733 not found on theTVDB, not adding the show: error Connection error HTTPSConnectionPool(host='thetvdb.com', port=443): Max retries exceeded with url: /api/F9C450E78D99172E/series/360733/en.xml (Caused by SSLError(SSLError("bad handshake: Error([('SSL routines', 'tls_process_server_certificate', 'certificate verify failed')],)",),)) while loading URL http://thetvdb.com/api/F9C450E78D99172E/series/360733/en.xml```

**Comment by papampi** [comment]
I'm getting multiple warnings on show refresh too :

```
2019-12-08 07:13:43 SHOWQUEUE-REFRESH :: There was an error trying to retrieve the image, aborting
2019-12-08 07:07:07 SHOWQUEUE-REFRESH :: Unable to look up show on theTVDB, not downloading images: error Connection error HTTPSConnectionPool(host='thetvdb.com', port=443): Max retries exceeded with url: /api/F9C450E78D99172E/series/370139/en.xml (Caused by ProxyError('Cannot connect to proxy.', error('Tunnel connection failed: 502 Bad Gateway',))) while loading URL http://thetvdb.com/api/F9C450E78D99172E/series/370139/en.xml
2019-12-08 06:50:35 SHOWQUEUE-REFRESH :: Unable to look up show on theTVDB, not downloading images: error Connection error HTTPSConnectionPool(host='thetvdb.com', port=443): Max retries exceeded with url: /api/F9C450E78D99172E/series/257655/en.xml (Caused by ProxyError('Cannot connect to proxy.', error('Tunnel connection failed: 502 Bad Gateway',))) while loading URL http://thetvdb.com/api/F9C450E78D99172E/series/257655/en.xml
2019-12-08 06:44:15 SHOWQUEUE-REFRESH :: Unable to look up show on theTVDB, not downloading images: error Connection error HTTPSConnectionPool(host='thetvdb.com', port=443): Max retries exceeded with url: /api/F9C450E78D99172E/series/259866/en.xml (Caused by ProxyError('Cannot connect to proxy.', error('Tunnel connection failed: 502 Bad Gateway',))) while loading URL http://thetvdb.com/api/F9C450E78D99172E/series/259866/en.xml
2019-12-08 05:55:56 SHOWQUEUE-REFRESH :: Unable to look up show on theTVDB, not downloading images: error Connection error HTTPSConnectionPool(host='thetvdb.com', port=443): Max retries exceeded with url: /api/F9C450E78D99172E/series/363940/en.xml (Caused by ProxyError('Cannot connect to proxy.', error('Tunnel connection failed: 502 Bad Gateway',))) while loading URL http://thetvdb.com/api/F9C450E78D99172E/series/363940/en.xml
2019-12-08 05:53:23 SHOWQUEUE-REFRESH :: Unable to look up show on theTVDB, not downloading images: error Connection error HTTPSConnectionPool(host='thetvdb.com', port=443): Max retries exceeded with url: /api/F9C450E78D99172E/series/352883/en.xml (Caused by ProxyError('Cannot connect to proxy.', error('Tunnel connection failed: 502 Bad Gateway',))) while loading URL http://thetvdb.com/api/F9C450E78D99172E/series/352883/en.xml
2019-12-08 05:36:56 SHOWQUEUE-FORCE-UPDATE :: theTVDB timed out, unable to update episodes from theTVDB
2019-12-08 05:35:29 SHOWQUEUE-REFRESH :: Unable to look up show on theTVDB, not downloading images: error Connection error HTTPSConnectionPool(host='thetvdb.com', port=443): Max retries exceeded with url: /api/F9C450E78D99172E/series/361558/en.xml (Caused by ProxyError('Cannot connect to proxy.', error('Tunnel connection failed: 502 Bad Gateway',))) while loading URL http://thetvdb.com/api/F9C450E78D99172E/series/361558/en.xml
2019-12-08 05:25:56 SHOWQUEUE-REFRESH :: Unable to look up show on theTVDB, not downloading images: error Connection error HTTPSConnectionPool(host='thetvdb.com', port=443): Max retries exceeded with url: /api/F9C450E78D99172E/series/332802/en.xml (Caused by ProxyError('Cannot connect to proxy.', error('Tunnel connection failed: 502 Bad Gateway',))) while loading URL http://thetvdb.com/api/F9C450E78D99172E/series/332802/en.xml
2019-12-08 05:24:43 SHOWQUEUE-REFRESH :: Unable to look up show on theTVDB, not downloading images: error Connection error HTTPSConnectionPool(host='thetvdb.com', port=443): Max retries exceeded with url: /api/F9C450E78D99172E/series/338499/en.xml (Caused by ProxyError('Cannot connect to proxy.', error('Tunnel connection failed: 502 Bad Gateway',))) while loading URL http://thetvdb.com/api/F9C450E78D99172E/series/338499/en.xml
2019-12-08 04:11:22 SHOWQUEUE-FORCE-UPDATE :: Unable to contact theTVDB, aborting: Connection error HTTPSConnectionPool(host='thetvdb.com', port=443): Max retries exceeded with url: /api/F9C450E78D99172E/series/258541/en.xml (Caused by ProxyError('Cannot connect to proxy.', error('Tunnel connection failed: 502 Bad Gateway',))) while loading URL http://thetvdb.com/api/F9C450E78D99172E/series/258541/en.xml
2019-12-08 03:56:30 SHOWQUEUE-REFRESH :: Unable to look up show on theTVDB, not downloading images: error Connection error HTTPSConnectionPool(host='thetvdb.com', port=443): Max retries exceeded with url: /api/F9C450E78D99172E/series/301236/en.xml (Caused by ProxyError('Cannot connect to proxy.', error('Tunnel connection failed: 502 Bad Gateway',))) while loading URL http://thetvdb.com/api/F9C450E78D99172E/series/301236/en.xml
2019-12-08 03:55:14 SHOWQUEUE-REFRESH :: Unable to look up show on theTVDB, not downloading images: error Connection error HTTPSConnectionPool(host='thetvdb.com', port=443): Max retries exceeded with url: /api/F9C450E78D99172E/series/340976/en.xml (Caused by ProxyError('Cannot connect to proxy.', error('Tunnel connection failed: 502 Bad Gateway',))) while loading URL http://thetvdb.com/api/F9C450E78D99172E/series/340976/en.xml
2019-12-08 03:33:41 SHOWQUEUE-REFRESH :: Unable to look up show on theTVDB, not downloading images: error Connection error HTTPSConnectionPool(host='thetvdb.com', port=443): Max retries exceeded with url: /api/F9C450E78D99172E/series/314442/en.xml (Caused by ProxyError('Cannot connect to proxy.', error('Tunnel connection failed: 502 Bad Gateway',))) while loading URL http://thetvdb.com/api/F9C450E78D99172E/series/314442/en.xml
```

**Comment by SimonMellerin** [comment]
Same issue here !

**Comment by SimonMellerin** [comment]
should be resolved by https://github.com/SickChill/SickChill/pull/5738

**Comment by rcvfdmark** [comment]
#5738 didn't fix it. Still getting certificate verify errors on show refresh, and new episodes aren't loading properly.

**Comment by ThrustVector** [comment]
Yhe same here. Still getting SSL errors when tryingto add shows.

**Comment by shropshirehobbit** [comment]
yes same here.  Just updated and still seeing the same issue.

**Comment by miigotu** [comment]
Fixed in develop, it will be released to master as soon as it is tested by more people.

**Comment by miigotu** [comment]
If anyone is still having this issue, ping me
