### ISSUE TITLE
Kodi notifications broke

### ISSUE THREAD

**Issue by basrieter** [SickChill/SickChill#5981]
### Before submitting your issue:

Enable debug logging in SickChill settings, reproduce the error (be sure to disable after the bug is fixed). it seem to have broken in 8fa4b4d90f4b9454ac45d3cec987be140a250de6: it worked before. 

Branch/Commit: master
OS: Windows 10
Browser: Chrome
What you did: Try to send a notification to Kodi
What happened: "Test KODI notice failed to ....."
What you expected:  "Test KODI notice sent successfully to ....."
Logs:
```
<nothing is logged while trying to connect to Kodi>
```

**Comment by miigotu** [comment]
Kodi 12+?

**Comment by rover1955** [comment]
Same issue here.  Kodi 18.5 and  Sickchill on Windows 10.  Both on localhost, same PC.
 SickChill Info: 
Branch: master 
Commit: 09207fe0680c8a8fd7b9b93127f28b62b6de3732 
Version: v2020.02.11-3 
Database Version: 44.4 
Python Version: 2.7.17 (v2.7.17:c2f86d86e6, Oct 19 2019, 21:01:17) [MSC v.1500 64 bit (AMD64)] 
SSL Version: OpenSSL 1.0.2t 10 Sep 2019 
OS: Windows-10-10.0.18362 

Was working but stopped.  Did a fresh install of Sickchill using the windows installer.  Fails.

Used an old installation and it connects OK.

SickChill Info: 
Branch: master 
Commit: e094759640ca61c5c033bf1ff9d33bc7fc1ba857 
Database Version: 44.0 
Python Version: 2.7.13 (v2.7.13:a06454b1afa1, Dec 17 2016, 20:53:40) [MSC v.1500 64 bit (AMD64)] 
SSL Version: OpenSSL 1.0.2j 26 Sep 2016 
 OS: Windows-10-10.0.18362

**Comment by rkorn86** [comment]
Same issue with kodi 18 and latest sickchill running inside docker. Even test notification fails without log message.

**Comment by miigotu** [comment]
What Version of Kodi

**Comment by rkorn86** [comment]
Libreelec 9.2.0 with kodi 18.5

Am 15. Februar 2020 17:01:30 schrieb miigotu <notifications@github.com>:

**Comment by rkorn86** [comment]
Everything worked about 20 commits ago

Am 15. Februar 2020 17:01:30 schrieb miigotu <notifications@github.com>:

**Comment by kyuuk** [comment]
i put a comment on code where i think the problem is 
[comment on kodi.py](https://github.com/SickChill/SickChill/commit/8fa4b4d90f4b9454ac45d3cec987be140a250de6#r37311594)

so it should be fixed soon, no need to post more ;)

**Comment by basrieter** [comment]
The test message is still not OK:

![image](https://user-images.githubusercontent.com/1310443/74594743-0591fc00-503a-11ea-9822-00dd5a512373.png)

**Comment by miigotu** [comment]
What is not ok about the test message? If it fails to an ip if says that one failed, and says it succeeds for the ones it succeeds for.

**Comment by basrieter** [comment]
...but I only have 1 configured and the blurred out part is the same host-name

**Comment by miigotu** [comment]
Idk why, but I know you dont need the :8080 on there antymore ^

**Comment by rover1955** [comment]
Removed the :8080 as well.  Works fine now.  Thank you.
