### ISSUE TITLE
Server Status Show Queue Frozen

### ISSUE THREAD

**Issue by ronrosenfeld** [SickChill/SickChill#6053]
### Before submitting your issue:

Enable debug logging in SickChill settings, reproduce the error (be sure to disable after the bug is fixed)

Branch: master 
Commit: 9fdab4c562732ec611186af64bcb1e8897879ff3 
Database Version: 44.1 
OS: Docker on Synology NAS
Browser: Edge
What you did:  Shows had `This show is queued and awaiting an update.` banner so I checked `Server Status` 
What happened: I observed a large number of shows in the queue type: `Force Update` and the first show in the list has now been there for hours.  Added time: 2020-03-05 04:54:26 (current time is 2020-03-05 09:25:00)
What you expected: Shows to be processed from time to time and disappear from the queue

Relevant Log entries from around the time the shows were added to the queue.
```
2020-03-05 04:54:20 INFO     CHECKVERSION :: Checking for updates using SOURCE
2020-03-05 04:54:23 INFO     SHOWUPDATER :: ShowUpdater for tvdb Api V3 starting
2020-03-05 04:54:26 INFO     SHOWUPDATER :: Last update: 2020-03-04 04:26:31
```
**Addendum**

I enabled `debug` mode and stopped and restarted Sickchill.
This emptied out the queue, but it filled up again this morning. 
And it is again stuck on the first episode.

What I think are the relevant log entries:

```
2020-03-07 04:29:22 DEBUG    SHOWUPDATER :: Starting new thread: SHOWUPDATER
2020-03-07 04:29:22 INFO     SHOWUPDATER :: ShowUpdater for tvdb Api V3 starting
2020-03-07 04:29:24 DEBUG    CHECKVERSION :: Starting new thread: CHECKVERSION
2020-03-07 04:29:24 INFO     CHECKVERSION :: Checking for updates using SOURCE
2020-03-07 04:29:29 INFO     SHOWUPDATER :: Last update: 2020-03-06 04:54:39
2020-03-07 04:29:31 DEBUG    SHOWQUEUE-FORCE-UPDATE :: Beginning update of Killing Eve
2020-03-07 04:29:31 DEBUG    SHOWQUEUE-FORCE-UPDATE :: Retrieving show info from theTVDB
2020-03-07 04:29:31 DEBUG    SHOWQUEUE-FORCE-UPDATE :: 340959: Loading show info from theTVDB
2020-03-07 04:29:38 DEBUG    SHOWQUEUE-FORCE-UPDATE :: Retrieving show info from IMDb
2020-03-07 04:29:39 DEBUG    SHOWQUEUE-FORCE-UPDATE :: 340959: Loading show info from IMDb
2020-03-07 04:29:42 DEBUG    CHECKVERSION :: cur_commit = 9fdab4c562732ec611186af64bcb1e8897879ff3, newest_commit = 9fdab4c562732ec611186af64bcb1e8897879ff3, num_commits_behind = 0
2020-03-07 04:29:42 DEBUG    CHECKVERSION :: check_for_new_news: Checking GitHub for latest news.
2020-03-07 04:30:03 DEBUG    SHOWQUEUE-FORCE-UPDATE :: 340959: Obtained info from IMDb ->{u'rating': u'', u'votes': u'', u'countries': u'', u'title': u'', u'genres': u'', u'imdb_id': u'tt7016936', u'country_codes': u'', u'year': u'', u'certificates': u'', u'runtimes': u'40', u'akas': u'', u'last_update': 737491}
2020-03-07 04:30:03 DEBUG    SHOWQUEUE-FORCE-UPDATE :: 340959: Saving to database: Killing Eve
2020-03-07 04:30:03 DEBUG    SHOWQUEUE-FORCE-UPDATE :: Loading all episodes from the database
2020-03-07 04:30:03 DEBUG    SHOWQUEUE-FORCE-UPDATE :: 340959: Not curSeason in scannedEps
2020-03-07 04:30:03 DEBUG    SHOWQUEUE-FORCE-UPDATE :: 340959: Loading Killing Eve S01E01 from the DB
2020-03-07 04:30:03 DEBUG    SHOWQUEUE-FORCE-UPDATE :: 340959: Loading Killing Eve S01E02 from the DB
2020-03-07 04:30:03 DEBUG    SHOWQUEUE-FORCE-UPDATE :: 340959: Loading Killing Eve S01E03 from the DB
2020-03-07 04:30:03 DEBUG    SHOWQUEUE-FORCE-UPDATE :: 340959: Loading Killing Eve S01E04 from the DB
2020-03-07 04:30:03 DEBUG    SHOWQUEUE-FORCE-UPDATE :: 340959: Loading Killing Eve S01E05 from the DB
2020-03-07 04:30:03 DEBUG    SHOWQUEUE-FORCE-UPDATE :: 340959: Loading Killing Eve S01E06 from the DB
2020-03-07 04:30:03 DEBUG    SHOWQUEUE-FORCE-UPDATE :: 340959: Loading Killing Eve S01E07 from the DB
2020-03-07 04:30:03 DEBUG    SHOWQUEUE-FORCE-UPDATE :: 340959: Loading Killing Eve S01E08 from the DB
2020-03-07 04:30:03 DEBUG    SHOWQUEUE-FORCE-UPDATE :: 340959: Not curSeason in scannedEps
2020-03-07 04:30:03 DEBUG    SHOWQUEUE-FORCE-UPDATE :: 340959: Loading Killing Eve S02E01 from the DB
2020-03-07 04:30:03 DEBUG    SHOWQUEUE-FORCE-UPDATE :: 340959: Loading Killing Eve S02E02 from the DB
2020-03-07 04:30:03 DEBUG    SHOWQUEUE-FORCE-UPDATE :: 340959: Loading Killing Eve S02E03 from the DB
2020-03-07 04:30:03 DEBUG    SHOWQUEUE-FORCE-UPDATE :: 340959: Loading Killing Eve S02E04 from the DB
2020-03-07 04:30:03 DEBUG    SHOWQUEUE-FORCE-UPDATE :: 340959: Loading Killing Eve S02E05 from the DB
2020-03-07 04:30:03 DEBUG    SHOWQUEUE-FORCE-UPDATE :: 340959: Loading Killing Eve S02E06 from the DB
2020-03-07 04:30:03 DEBUG    SHOWQUEUE-FORCE-UPDATE :: 340959: Loading Killing Eve S02E07 from the DB
2020-03-07 04:30:03 DEBUG    SHOWQUEUE-FORCE-UPDATE :: 340959: Loading Killing Eve S02E08 from the DB
2020-03-07 04:30:03 DEBUG    SHOWQUEUE-FORCE-UPDATE :: Setter sets location to /tv/Killing Eve/S02E08/You're Mine 720p WEB-DL x264.mkv
2020-03-07 04:30:03 DEBUG    SHOWQUEUE-FORCE-UPDATE :: Checking if /tv/Killing Eve/S02E08/metadata/You're Mine 720p WEB-DL x264.xml exists: True
2020-03-07 04:30:03 DEBUG    SHOWQUEUE-FORCE-UPDATE :: 340959: Not curSeason in scannedEps
2020-03-07 04:30:03 DEBUG    SHOWQUEUE-FORCE-UPDATE :: 340959: Loading Killing Eve S03E01 from the DB
2020-03-07 04:30:03 DEBUG    SHOWQUEUE-FORCE-UPDATE :: 340959: Finished loading all episodes for Killing Eve from the DB
2020-03-07 04:30:03 DEBUG    SHOWQUEUE-FORCE-UPDATE :: Loading all episodes from theTVDB
2020-03-07 04:30:03 DEBUG    SHOWQUEUE-FORCE-UPDATE :: 340959: Loading all episodes from theTVDB...
2020-03-07 04:30:07 DEBUG    SHOWQUEUE-FORCE-UPDATE :: 340959: The absolute number for S01E01 is: 1 
2020-03-07 04:30:07 DEBUG    SHOWQUEUE-FORCE-UPDATE :: Not touching status [ Skipped ] It could be skipped/ignored/snatched/archived
2020-03-07 04:30:07 DEBUG    SHOWQUEUE-FORCE-UPDATE :: 340959: Not creating SQL queue - record is not dirty
2020-03-07 04:30:08 DEBUG    SHOWQUEUE-FORCE-UPDATE :: 340959: The absolute number for S01E02 is: 2 
2020-03-07 04:30:08 DEBUG    SHOWQUEUE-FORCE-UPDATE :: Not touching status [ Skipped ] It could be skipped/ignored/snatched/archived
2020-03-07 04:30:08 DEBUG    SHOWQUEUE-FORCE-UPDATE :: 340959: Not creating SQL queue - record is not dirty
2020-03-07 04:30:10 DEBUG    SHOWQUEUE-FORCE-UPDATE :: 340959: The absolute number for S01E03 is: 3 
2020-03-07 04:30:10 DEBUG    SHOWQUEUE-FORCE-UPDATE :: Not touching status [ Skipped ] It could be skipped/ignored/snatched/archived
2020-03-07 04:30:10 DEBUG    SHOWQUEUE-FORCE-UPDATE :: 340959: Not creating SQL queue - record is not dirty
2020-03-07 04:30:13 DEBUG    SHOWQUEUE-FORCE-UPDATE :: 340959: The absolute number for S01E04 is: 4 
2020-03-07 04:30:13 DEBUG    SHOWQUEUE-FORCE-UPDATE :: Not touching status [ Skipped ] It could be skipped/ignored/snatched/archived
2020-03-07 04:30:13 DEBUG    SHOWQUEUE-FORCE-UPDATE :: 340959: Not creating SQL queue - record is not dirty
2020-03-07 04:30:14 DEBUG    SHOWQUEUE-FORCE-UPDATE :: 340959: The absolute number for S01E05 is: 5 
2020-03-07 04:30:14 DEBUG    SHOWQUEUE-FORCE-UPDATE :: Not touching status [ Skipped ] It could be skipped/ignored/snatched/archived
2020-03-07 04:30:14 DEBUG    SHOWQUEUE-FORCE-UPDATE :: 340959: Not creating SQL queue - record is not dirty
2020-03-07 04:30:15 DEBUG    SHOWQUEUE-FORCE-UPDATE :: 340959: The absolute number for S01E06 is: 6 
2020-03-07 04:30:15 DEBUG    SHOWQUEUE-FORCE-UPDATE :: Not touching status [ Skipped ] It could be skipped/ignored/snatched/archived
2020-03-07 04:30:15 DEBUG    SHOWQUEUE-FORCE-UPDATE :: 340959: Not creating SQL queue - record is not dirty
2020-03-07 04:30:18 DEBUG    SHOWQUEUE-FORCE-UPDATE :: 340959: The absolute number for S01E07 is: 7 
2020-03-07 04:30:18 DEBUG    SHOWQUEUE-FORCE-UPDATE :: Not touching status [ Skipped ] It could be skipped/ignored/snatched/archived
2020-03-07 04:30:18 DEBUG    SHOWQUEUE-FORCE-UPDATE :: 340959: Not creating SQL queue - record is not dirty
2020-03-07 04:30:20 DEBUG    SHOWQUEUE-FORCE-UPDATE :: 340959: The absolute number for S01E08 is: 8 
2020-03-07 04:30:20 DEBUG    SHOWQUEUE-FORCE-UPDATE :: Not touching status [ Archived (720p WEB-DL) ] It could be skipped/ignored/snatched/archived
2020-03-07 04:30:20 DEBUG    SHOWQUEUE-FORCE-UPDATE :: 340959: Not creating SQL queue - record is not dirty
```

**Comment by miigotu** [comment]
TVDB probably blocking too many requests.

**Comment by ronrosenfeld** [comment]
This happens once a day, and is the only time this process is triggered (by SickChill).  Then the queue stays completely blocked indefinitely, unless I do a restart.

**Comment by ronrosenfeld** [comment]
If the problem is "too many requests", is there any way to clear the queue (other than by restarting SC), and/or throttling the requests so this doesn't happen?

**Comment by miigotu** [comment]
6ffe43b1fe90abfcb1b6f57a2f3fd76e43f3cdc3

**Comment by ronrosenfeld** [comment]
I just updated to fcc03b6a142401188adcfea7126d671b369df47a which seems to be the latest on Master.  How do I force an update to 6ffe43b?

**Comment by miigotu** [comment]
https://github.com/SickChill/SickChill/commit/fcc03b6a142401188adcfea7126d671b369df47a is after https://github.com/SickChill/SickChill/commit/6ffe43b1fe90abfcb1b6f57a2f3fd76e43f3cdc3

**Comment by ronrosenfeld** [comment]
Thank you.  I'll see what happens tomorrow AM when `FORCE-UPDATE` runs again.

**Comment by ronrosenfeld** [comment]
This latest update does not seem to have fixed the problem.

With the version: https://github.com/SickChill/SickChill/commit/fcc03b6a142401188adcfea7126d671b369df47a I am still seeing about 40 shows stuck in the backlog.  But today, instead of them all being to type `Force Update`, some of them are of type `Refresh`

![image](https://user-images.githubusercontent.com/18516066/76161345-02ee6800-6109-11ea-9726-a0b9ae8d8428.png)

**Comment by miigotu** [comment]
Stop messing with it and let it run lol. Unless the log shows something, there is nothing to do.

**Comment by ronrosenfeld** [comment]
The logs indicate that the `Force Update` queued shows are the one's that get "stuck"  The shows that are not "stuck" in there don't have any entries indicating `SHOWQUEUE-FORCE-UPDATE`

Does this backlog in the QUEUE not have any side-effects?

Here are the log entries relative to `Young Sheldon`, but I don't know if they show anything useful.

```

3/8/2020   4:13 | DEBUG | SHOWQUEUE-FORCE-UPDATE | Beginning update of Young   Sheldon
-- | -- | -- | --
3/8/2020   4:13 | DEBUG | SHOWQUEUE-FORCE-UPDATE | Retrieving show info from theTVDB
3/8/2020 4:13 | DEBUG | SHOWQUEUE-FORCE-UPDATE | 328724:   Loading show info from theTVDB
3/8/2020   4:13 | DEBUG | SHOWQUEUE-FORCE-UPDATE | Retrieving show info from IMDb
3/8/2020 4:13 | DEBUG | SHOWQUEUE-FORCE-UPDATE | 328724:   Loading show info from IMDb
3/8/2020   4:14 | DEBUG | SHOWQUEUE-FORCE-UPDATE | 328724: Obtained info from IMDb   ->{u'rating': u'', u'votes': u'', u'countries': u'', u'title': u'',   u'genres': u'', u'imdb_id': u'tt6226232', u'country_codes': u'', u'year':   u'', u'certificates': u'', u'runtimes': u'20', u'akas': u'', u'last_update': 737492}
3/8/2020 4:14 | DEBUG | SHOWQUEUE-FORCE-UPDATE | 328724:   Saving to database: Young Sheldon
3/8/2020   4:14 | DEBUG | SHOWQUEUE-FORCE-UPDATE | Loading all episodes from the database
3/8/2020 4:14 | DEBUG | SHOWQUEUE-FORCE-UPDATE | 328724:   Not curSeason in scannedEps
3/8/2020   4:14 | DEBUG | SHOWQUEUE-FORCE-UPDATE | 328724: Loading Young Sheldon S01E01   from the DB
3/8/2020 4:14 | DEBUG | SHOWQUEUE-FORCE-UPDATE | 328724:   Loading Young Sheldon S01E02 from the DB
3/8/2020   4:14 | DEBUG | SHOWQUEUE-FORCE-UPDATE | 328724: Loading Young Sheldon S01E03   from the DB
3/8/2020 4:14 | DEBUG | SHOWQUEUE-FORCE-UPDATE | 328724:   Loading Young Sheldon S01E04 from the DB
3/8/2020   4:14 | DEBUG | SHOWQUEUE-FORCE-UPDATE | 328724: Loading Young Sheldon S01E05   from the DB
3/8/2020 4:14 | DEBUG | SHOWQUEUE-FORCE-UPDATE | 328724:   Loading Young Sheldon S01E06 from the DB
3/8/2020   4:14 | DEBUG | SHOWQUEUE-FORCE-UPDATE | 328724: Loading Young Sheldon S01E07   from the DB
3/8/2020 4:14 | DEBUG | SHOWQUEUE-FORCE-UPDATE | 328724:   Loading Young Sheldon S01E08 from the DB
3/8/2020   4:14 | DEBUG | SHOWQUEUE-FORCE-UPDATE | 328724: Loading Young Sheldon S01E09   from the DB
3/8/2020 4:14 | DEBUG | SHOWQUEUE-FORCE-UPDATE | 328724:   Loading Young Sheldon S01E10 from the DB
3/8/2020   4:14 | DEBUG | SHOWQUEUE-FORCE-UPDATE | 328724: Loading Young Sheldon S01E11   from the DB
3/8/2020 4:14 | DEBUG | SHOWQUEUE-FORCE-UPDATE | 328724:   Loading Young Sheldon S01E12 from the DB
3/8/2020   4:14 | DEBUG | SHOWQUEUE-FORCE-UPDATE | 328724: Loading Young Sheldon S01E13   from the DB
3/8/2020 4:14 | DEBUG | SHOWQUEUE-FORCE-UPDATE | 328724:   Loading Young Sheldon S01E14 from the DB
3/8/2020   4:14 | DEBUG | SHOWQUEUE-FORCE-UPDATE | 328724: Loading Young Sheldon S01E15   from the DB
3/8/2020 4:14 | DEBUG | SHOWQUEUE-FORCE-UPDATE | 328724:   Loading Young Sheldon S01E16 from the DB
3/8/2020   4:14 | DEBUG | SHOWQUEUE-FORCE-UPDATE | 328724: Loading Young Sheldon S01E17   from the DB
3/8/2020 4:14 | DEBUG | SHOWQUEUE-FORCE-UPDATE | 328724:   Loading Young Sheldon S01E18 from the DB
3/8/2020   4:14 | DEBUG | SHOWQUEUE-FORCE-UPDATE | 328724: Loading Young Sheldon S01E19   from the DB
3/8/2020 4:14 | DEBUG | SHOWQUEUE-FORCE-UPDATE | 328724:   Loading Young Sheldon S01E20 from the DB
3/8/2020   4:14 | DEBUG | SHOWQUEUE-FORCE-UPDATE | 328724: Loading Young Sheldon S01E21   from the DB
3/8/2020 4:14 | DEBUG | SHOWQUEUE-FORCE-UPDATE | 328724:   Loading Young Sheldon S01E22 from the DB
3/8/2020   4:14 | DEBUG | SHOWQUEUE-FORCE-UPDATE | 328724: Not curSeason in scannedEps
3/8/2020 4:14 | DEBUG | SHOWQUEUE-FORCE-UPDATE | 328724:   Loading Young Sheldon S02E01 from the DB
3/8/2020   4:14 | DEBUG | SHOWQUEUE-FORCE-UPDATE | 328724: Loading Young Sheldon S02E02   from the DB
3/8/2020 4:14 | DEBUG | SHOWQUEUE-FORCE-UPDATE | 328724:   Loading Young Sheldon S02E03 from the DB
3/8/2020   4:14 | DEBUG | SHOWQUEUE-FORCE-UPDATE | 328724: Loading Young Sheldon S02E04   from the DB
3/8/2020 4:14 | DEBUG | SHOWQUEUE-FORCE-UPDATE | 328724:   Loading Young Sheldon S02E05 from the DB
3/8/2020   4:14 | DEBUG | SHOWQUEUE-FORCE-UPDATE | 328724: Loading Young Sheldon S02E06   from the DB
3/8/2020 4:14 | DEBUG | SHOWQUEUE-FORCE-UPDATE | 328724:   Loading Young Sheldon S02E07 from the DB
3/8/2020   4:14 | DEBUG | SHOWQUEUE-FORCE-UPDATE | 328724: Loading Young Sheldon S02E08   from the DB
3/8/2020 4:14 | DEBUG | SHOWQUEUE-FORCE-UPDATE | 328724:   Loading Young Sheldon S02E09 from the DB
3/8/2020   4:14 | DEBUG | SHOWQUEUE-FORCE-UPDATE | 328724: Loading Young Sheldon S02E10   from the DB
3/8/2020 4:14 | DEBUG | SHOWQUEUE-FORCE-UPDATE | 328724:   Loading Young Sheldon S02E11 from the DB
3/8/2020   4:14 | DEBUG | SHOWQUEUE-FORCE-UPDATE | 328724: Loading Young Sheldon S02E12   from the DB
3/8/2020 4:14 | DEBUG | SHOWQUEUE-FORCE-UPDATE | 328724:   Loading Young Sheldon S02E13 from the DB
3/8/2020   4:14 | DEBUG | SHOWQUEUE-FORCE-UPDATE | 328724: Loading Young Sheldon S02E14   from the DB
3/8/2020 4:14 | DEBUG | SHOWQUEUE-FORCE-UPDATE | 328724:   Loading Young Sheldon S02E15 from the DB
3/8/2020   4:14 | DEBUG | SHOWQUEUE-FORCE-UPDATE | 328724: Loading Young Sheldon S02E16   from the DB
3/8/2020 4:14 | DEBUG | SHOWQUEUE-FORCE-UPDATE | 328724:   Loading Young Sheldon S02E17 from the DB
3/8/2020   4:14 | DEBUG | SHOWQUEUE-FORCE-UPDATE | 328724: Loading Young Sheldon S02E18   from the DB
3/8/2020 4:14 | DEBUG | SHOWQUEUE-FORCE-UPDATE | 328724:   Loading Young Sheldon S02E19 from the DB
3/8/2020   4:14 | DEBUG | SHOWQUEUE-FORCE-UPDATE | 328724: Loading Young Sheldon S02E20   from the DB
3/8/2020 4:14 | DEBUG | SHOWQUEUE-FORCE-UPDATE | 328724:   Loading Young Sheldon S02E21 from the DB
3/8/2020   4:14 | DEBUG | SHOWQUEUE-FORCE-UPDATE | 328724: Loading Young Sheldon S02E22   from the DB
3/8/2020 4:14 | DEBUG | SHOWQUEUE-FORCE-UPDATE | 328724:   Not curSeason in scannedEps
3/8/2020   4:14 | DEBUG | SHOWQUEUE-FORCE-UPDATE | 328724: Loading Young Sheldon S03E01   from the DB
3/8/2020 4:14 | DEBUG | SHOWQUEUE-FORCE-UPDATE | 328724:   Loading Young Sheldon S03E02 from the DB
3/8/2020   4:14 | DEBUG | SHOWQUEUE-FORCE-UPDATE | 328724: Loading Young Sheldon S03E03   from the DB
3/8/2020 4:14 | DEBUG | SHOWQUEUE-FORCE-UPDATE | 328724:   Loading Young Sheldon S03E04 from the DB
3/8/2020   4:14 | DEBUG | SHOWQUEUE-FORCE-UPDATE | 328724: Loading Young Sheldon S03E05   from the DB
3/8/2020 4:14 | DEBUG | SHOWQUEUE-FORCE-UPDATE | 328724:   Loading Young Sheldon S03E06 from the DB
3/8/2020   4:14 | DEBUG | SHOWQUEUE-FORCE-UPDATE | 328724: Loading Young Sheldon S03E07   from the DB
3/8/2020 4:14 | DEBUG | SHOWQUEUE-FORCE-UPDATE | Setter   sets location to /tv/Young Sheldon/S03E07/Pongo Pygmaeus and a Culture that   Encourages Spitting SDTV.mkv
3/8/2020   4:14 | DEBUG | SHOWQUEUE-FORCE-UPDATE | 328724: Loading Young Sheldon S03E08   from the DB
3/8/2020 4:14 | DEBUG | SHOWQUEUE-FORCE-UPDATE | 328724:   Loading Young Sheldon S03E09 from the DB
3/8/2020   4:14 | DEBUG | SHOWQUEUE-FORCE-UPDATE | Setter sets location to /tv/Young   Sheldon/S03E09/A Party Invitation, Football Grapes and an Earth Chicken 720p   HDTV.mkv
3/8/2020 4:14 | DEBUG | SHOWQUEUE-FORCE-UPDATE | 328724:   Loading Young Sheldon S03E10 from the DB
3/8/2020   4:14 | DEBUG | SHOWQUEUE-FORCE-UPDATE | Setter sets location to /tv/Young   Sheldon/S03E10/Teenager Soup and a Little Ball of Fib 720p HDTV.mkv
3/8/2020 4:14 | DEBUG | SHOWQUEUE-FORCE-UPDATE | 328724:   Loading Young Sheldon S03E11 from the DB
3/8/2020   4:14 | DEBUG | SHOWQUEUE-FORCE-UPDATE | Setter sets location to /tv/Young   Sheldon/S03E11/A Live Chicken, a Fried Chicken and Holy Matrimony 720p   HDTV.mkv
3/8/2020 4:14 | DEBUG | SHOWQUEUE-FORCE-UPDATE | 328724:   Loading Young Sheldon S03E12 from the DB
3/8/2020   4:14 | DEBUG | SHOWQUEUE-FORCE-UPDATE | Setter sets location to /tv/Young   Sheldon/S03E12/Body Glitter and a Mall Safety Kit 720p HDTV.mkv
3/8/2020 4:14 | DEBUG | SHOWQUEUE-FORCE-UPDATE | 328724:   Loading Young Sheldon S03E16 from the DB
3/8/2020   4:14 | DEBUG | SHOWQUEUE-FORCE-UPDATE | Setter sets location to /tv/Young   Sheldon/S03E16/Pasadena 720p HDTV x264.mkv
3/8/2020 4:14 | DEBUG | SHOWQUEUE-FORCE-UPDATE | Checking   if /tv/Young Sheldon/S03E16/metadata/Pasadena 720p HDTV x264.xml exists: True
3/8/2020   4:14 | DEBUG | SHOWQUEUE-FORCE-UPDATE | 328724: Finished loading all episodes   for Young Sheldon from the DB
3/8/2020 4:14 | DEBUG | SHOWQUEUE-FORCE-UPDATE | Loading   all episodes from theTVDB
3/8/2020   4:14 | DEBUG | SHOWQUEUE-FORCE-UPDATE | 328724: Loading all episodes from   theTVDB...
3/8/2020 4:14 | DEBUG | SHOWQUEUE-FORCE-UPDATE | 328724:   The absolute number for S01E01 is: 1
3/8/2020   4:14 | DEBUG | SHOWQUEUE-FORCE-UPDATE | Not touching status [ Skipped ] It could   be skipped/ignored/snatched/archived
3/8/2020 4:14 | DEBUG | SHOWQUEUE-FORCE-UPDATE | 328724:   Not creating SQL queue - record is not dirty
3/8/2020   4:14 | DEBUG | SHOWQUEUE-FORCE-UPDATE | 328724: The absolute number for S01E03   is: 3
3/8/2020 4:14 | DEBUG | SHOWQUEUE-FORCE-UPDATE | Not   touching status [ Skipped ] It could be skipped/ignored/snatched/archived
3/8/2020   4:14 | DEBUG | SHOWQUEUE-FORCE-UPDATE | 328724: Not creating SQL queue - record   is not dirty
3/8/2020 4:14 | DEBUG | SHOWQUEUE-FORCE-UPDATE | 328724:   The absolute number for S01E02 is: 2
3/8/2020   4:14 | DEBUG | SHOWQUEUE-FORCE-UPDATE | Not touching status [ Skipped ] It could   be skipped/ignored/snatched/archived
3/8/2020 4:14 | DEBUG | SHOWQUEUE-FORCE-UPDATE | 328724:   Not creating SQL queue - record is not dirty
3/8/2020   4:14 | DEBUG | SHOWQUEUE-FORCE-UPDATE | 328724: The absolute number for S01E04   is: 4
3/8/2020 4:14 | DEBUG | SHOWQUEUE-FORCE-UPDATE | Not   touching status [ Skipped ] It could be skipped/ignored/snatched/archived
3/8/2020   4:15 | DEBUG | SHOWQUEUE-FORCE-UPDATE | 328724: The absolute number for S01E05   is: 5
3/8/2020 4:15 | DEBUG | SHOWQUEUE-FORCE-UPDATE | Not   touching status [ Skipped ] It could be skipped/ignored/snatched/archived
3/8/2020   4:15 | DEBUG | SHOWQUEUE-FORCE-UPDATE | 328724: Not creating SQL queue - record   is not dirty
3/8/2020 4:15 | DEBUG | SHOWQUEUE-FORCE-UPDATE | 328724:   The absolute number for S01E06 is: 6
3/8/2020   4:15 | DEBUG | SHOWQUEUE-FORCE-UPDATE | Not touching status [ Skipped ] It could   be skipped/ignored/snatched/archived
3/8/2020 4:15 | DEBUG | SHOWQUEUE-FORCE-UPDATE | 328724:   Not creating SQL queue - record is not dirty
3/8/2020   4:15 | DEBUG | SHOWQUEUE-FORCE-UPDATE | 328724: The absolute number for S01E07   is: 7
3/8/2020 4:15 | DEBUG | SHOWQUEUE-FORCE-UPDATE | Not   touching status [ Skipped ] It could be skipped/ignored/snatched/archived
3/8/2020   4:15 | DEBUG | SHOWQUEUE-FORCE-UPDATE | 328724: Not creating SQL queue - record   is not dirty
3/8/2020 4:15 | DEBUG | SHOWQUEUE-FORCE-UPDATE | 328724:   The absolute number for S01E08 is: 8
3/8/2020   4:15 | DEBUG | SHOWQUEUE-FORCE-UPDATE | Not touching status [ Skipped ] It could   be skipped/ignored/snatched/archived
3/8/2020 4:15 | DEBUG | SHOWQUEUE-FORCE-UPDATE | 328724:   Not creating SQL queue - record is not dirty
3/8/2020   4:15 | DEBUG | SHOWQUEUE-FORCE-UPDATE | 328724: The absolute number for S01E09   is: 9
3/8/2020 4:15 | DEBUG | SHOWQUEUE-FORCE-UPDATE | Not   touching status [ Skipped ] It could be skipped/ignored/snatched/archived
3/8/2020   4:15 | DEBUG | SHOWQUEUE-FORCE-UPDATE | 328724: Not creating SQL queue - record   is not dirty
3/8/2020 4:15 | DEBUG | SHOWQUEUE-FORCE-UPDATE | 328724:   The absolute number for S01E10 is: 10
3/8/2020   4:15 | DEBUG | SHOWQUEUE-FORCE-UPDATE | Not touching status [ Skipped ] It could   be skipped/ignored/snatched/archived
3/8/2020 4:15 | DEBUG | SHOWQUEUE-FORCE-UPDATE | 328724:   Not creating SQL queue - record is not dirty
3/8/2020   4:15 | DEBUG | SHOWQUEUE-FORCE-UPDATE | 328724: The absolute number for S01E11   is: 11
3/8/2020 4:15 | DEBUG | SHOWQUEUE-FORCE-UPDATE | Not   touching status [ Skipped ] It could be skipped/ignored/snatched/archived
3/8/2020   4:15 | DEBUG | SHOWQUEUE-FORCE-UPDATE | 328724: Not creating SQL queue - record   is not dirty
3/8/2020 4:15 | DEBUG | SHOWQUEUE-FORCE-UPDATE | 328724:   The absolute number for S01E12 is: 12
3/8/2020   4:15 | DEBUG | SHOWQUEUE-FORCE-UPDATE | Not touching status [ Skipped ] It could   be skipped/ignored/snatched/archived
3/8/2020 4:15 | DEBUG | SHOWQUEUE-FORCE-UPDATE | 328724:   Not creating SQL queue - record is not dirty
3/8/2020   4:15 | DEBUG | SHOWQUEUE-FORCE-UPDATE | 328724: The absolute number for S01E13   is: 13
3/8/2020 4:15 | DEBUG | SHOWQUEUE-FORCE-UPDATE | Not   touching status [ Skipped ] It could be skipped/ignored/snatched/archived
3/8/2020   4:15 | DEBUG | SHOWQUEUE-FORCE-UPDATE | 328724: Not creating SQL queue - record   is not dirty
3/8/2020 4:15 | DEBUG | SHOWQUEUE-FORCE-UPDATE | 328724:   The absolute number for S01E14 is: 14
3/8/2020   4:15 | DEBUG | SHOWQUEUE-FORCE-UPDATE | Not touching status [ Skipped ] It could   be skipped/ignored/snatched/archived
3/8/2020 4:15 | DEBUG | SHOWQUEUE-FORCE-UPDATE | 328724:   Not creating SQL queue - record is not dirty
3/8/2020   4:15 | DEBUG | SHOWQUEUE-FORCE-UPDATE | 328724: The absolute number for S01E15   is: 15
3/8/2020 4:15 | DEBUG | SHOWQUEUE-FORCE-UPDATE | Not   touching status [ Skipped ] It could be skipped/ignored/snatched/archived
3/8/2020   4:15 | DEBUG | SHOWQUEUE-FORCE-UPDATE | 328724: Not creating SQL queue - record   is not dirty
3/8/2020 4:15 | DEBUG | SHOWQUEUE-FORCE-UPDATE | 328724:   The absolute number for S01E16 is: 16
3/8/2020   4:15 | DEBUG | SHOWQUEUE-FORCE-UPDATE | Not touching status [ Skipped ] It could   be skipped/ignored/snatched/archived
3/8/2020 4:15 | DEBUG | SHOWQUEUE-FORCE-UPDATE | 328724:   Not creating SQL queue - record is not dirty
3/8/2020   4:15 | DEBUG | SHOWQUEUE-FORCE-UPDATE | 328724: The absolute number for S01E17   is: 17
3/8/2020 4:15 | DEBUG | SHOWQUEUE-FORCE-UPDATE | Not   touching status [ Skipped ] It could be skipped/ignored/snatched/archived
3/8/2020   4:15 | DEBUG | SHOWQUEUE-FORCE-UPDATE | 328724: Not creating SQL queue - record   is not dirty
3/8/2020 4:15 | DEBUG | SHOWQUEUE-FORCE-UPDATE | 328724:   The absolute number for S01E18 is: 18
3/8/2020   4:15 | DEBUG | SHOWQUEUE-FORCE-UPDATE | Not touching status [ Skipped ] It could   be skipped/ignored/snatched/archived
3/8/2020 4:15 | DEBUG | SHOWQUEUE-FORCE-UPDATE | 328724:   Not creating SQL queue - record is not dirty
3/8/2020   4:15 | DEBUG | SHOWQUEUE-FORCE-UPDATE | 328724: The absolute number for S01E19   is: 19
3/8/2020 4:15 | DEBUG | SHOWQUEUE-FORCE-UPDATE | Not   touching status [ Skipped ] It could be skipped/ignored/snatched/archived
3/8/2020   4:15 | DEBUG | SHOWQUEUE-FORCE-UPDATE | 328724: Not creating SQL queue - record   is not dirty
3/8/2020 4:15 | DEBUG | SHOWQUEUE-FORCE-UPDATE | 328724:   The absolute number for S01E20 is: 20
3/8/2020   4:15 | DEBUG | SHOWQUEUE-FORCE-UPDATE | Not touching status [ Skipped ] It could   be skipped/ignored/snatched/archived
3/8/2020 4:15 | DEBUG | SHOWQUEUE-FORCE-UPDATE | 328724:   Not creating SQL queue - record is not dirty
3/8/2020   4:15 | DEBUG | SHOWQUEUE-FORCE-UPDATE | 328724: The absolute number for S01E21   is: 21
3/8/2020 4:15 | DEBUG | SHOWQUEUE-FORCE-UPDATE | Not   touching status [ Skipped ] It could be skipped/ignored/snatched/archived
3/8/2020   4:15 | DEBUG | SHOWQUEUE-FORCE-UPDATE | 328724: Not creating SQL queue - record   is not dirty
3/8/2020 4:15 | DEBUG | SHOWQUEUE-FORCE-UPDATE | 328724:   The absolute number for S01E22 is: 22
3/8/2020   4:15 | DEBUG | SHOWQUEUE-FORCE-UPDATE | Not touching status [ Skipped ] It could   be skipped/ignored/snatched/archived
3/8/2020 4:15 | DEBUG | SHOWQUEUE-FORCE-UPDATE | 328724:   Not creating SQL queue - record is not dirty
3/8/2020   4:15 | DEBUG | SHOWQUEUE-FORCE-UPDATE | 328724: The absolute number for S02E03   is: 25
3/8/2020 4:15 | DEBUG | SHOWQUEUE-FORCE-UPDATE | Not   touching status [ Skipped ] It could be skipped/ignored/snatched/archived
3/8/2020   4:15 | DEBUG | SHOWQUEUE-FORCE-UPDATE | 328724: Not creating SQL queue - record   is not dirty
3/8/2020 4:15 | DEBUG | SHOWQUEUE-FORCE-UPDATE | 328724:   The absolute number for S02E02 is: 24
3/8/2020   4:15 | DEBUG | SHOWQUEUE-FORCE-UPDATE | Not touching status [ Skipped ] It could   be skipped/ignored/snatched/archived
3/8/2020 4:15 | DEBUG | SHOWQUEUE-FORCE-UPDATE | 328724:   Not creating SQL queue - record is not dirty
3/8/2020   4:15 | DEBUG | SHOWQUEUE-FORCE-UPDATE | 328724: The absolute number for S02E01   is: 23
3/8/2020 4:15 | DEBUG | SHOWQUEUE-FORCE-UPDATE | Not   touching status [ Skipped ] It could be skipped/ignored/snatched/archived
3/8/2020   4:15 | DEBUG | SHOWQUEUE-FORCE-UPDATE | 328724: Not creating SQL queue - record   is not dirty
3/8/2020 4:15 | DEBUG | SHOWQUEUE-FORCE-UPDATE | 328724:   The absolute number for S02E04 is: 26
3/8/2020   4:15 | DEBUG | SHOWQUEUE-FORCE-UPDATE | Not touching status [ Skipped ] It could   be skipped/ignored/snatched/archived
3/8/2020 4:15 | DEBUG | SHOWQUEUE-FORCE-UPDATE | 328724:   Not creating SQL queue - record is not dirty
3/8/2020   4:15 | DEBUG | SHOWQUEUE-FORCE-UPDATE | 328724: The absolute number for S02E05   is: 27
3/8/2020 4:15 | DEBUG | SHOWQUEUE-FORCE-UPDATE | Not   touching status [ Skipped ] It could be skipped/ignored/snatched/archived
3/8/2020   4:15 | DEBUG | SHOWQUEUE-FORCE-UPDATE | 328724: Not creating SQL queue - record   is not dirty
3/8/2020 4:16 | DEBUG | SHOWQUEUE-FORCE-UPDATE | 328724:   The absolute number for S02E06 is: 28
3/8/2020   4:16 | DEBUG | SHOWQUEUE-FORCE-UPDATE | Not touching status [ Skipped ] It could   be skipped/ignored/snatched/archived
3/8/2020 4:16 | DEBUG | SHOWQUEUE-FORCE-UPDATE | 328724:   Not creating SQL queue - record is not dirty
3/8/2020   4:16 | DEBUG | SHOWQUEUE-FORCE-UPDATE | 328724: The absolute number for S02E07   is: 29
3/8/2020 4:16 | DEBUG | SHOWQUEUE-FORCE-UPDATE | Not   touching status [ Skipped ] It could be skipped/ignored/snatched/archived
3/8/2020   4:16 | DEBUG | SHOWQUEUE-FORCE-UPDATE | 328724: Not creating SQL queue - record   is not dirty
3/8/2020 4:16 | DEBUG | SHOWQUEUE-FORCE-UPDATE | 328724:   The absolute number for S02E08 is: 30
3/8/2020   4:16 | DEBUG | SHOWQUEUE-FORCE-UPDATE | Not touching status [ Skipped ] It could   be skipped/ignored/snatched/archived
3/8/2020 4:16 | DEBUG | SHOWQUEUE-FORCE-UPDATE | 328724:   Not creating SQL queue - record is not dirty
3/8/2020   4:16 | DEBUG | SHOWQUEUE-FORCE-UPDATE | 328724: The absolute number for S02E09   is: 31
3/8/2020 4:16 | DEBUG | SHOWQUEUE-FORCE-UPDATE | Not   touching status [ Skipped ] It could be skipped/ignored/snatched/archived
3/8/2020   4:16 | DEBUG | SHOWQUEUE-FORCE-UPDATE | 328724: Not creating SQL queue - record   is not dirty
3/8/2020 4:16 | DEBUG | SHOWQUEUE-FORCE-UPDATE | 328724:   The absolute number for S02E10 is: 32
3/8/2020   4:16 | DEBUG | SHOWQUEUE-FORCE-UPDATE | Not touching status [ Skipped ] It could   be skipped/ignored/snatched/archived
3/8/2020 4:16 | DEBUG | SHOWQUEUE-FORCE-UPDATE | 328724:   Not creating SQL queue - record is not dirty
3/8/2020   4:16 | DEBUG | SHOWQUEUE-FORCE-UPDATE | 328724: The absolute number for S02E11   is: 33
3/8/2020 4:16 | DEBUG | SHOWQUEUE-FORCE-UPDATE | Not   touching status [ Skipped ] It could be skipped/ignored/snatched/archived
3/8/2020   4:16 | DEBUG | SHOWQUEUE-FORCE-UPDATE | 328724: Not creating SQL queue - record   is not dirty
3/8/2020 4:16 | DEBUG | SHOWQUEUE-FORCE-UPDATE | 328724:   The absolute number for S02E12 is: 34
3/8/2020   4:16 | DEBUG | SHOWQUEUE-FORCE-UPDATE | Not touching status [ Skipped ] It could   be skipped/ignored/snatched/archived
3/8/2020 4:16 | DEBUG | SHOWQUEUE-FORCE-UPDATE | 328724:   Not creating SQL queue - record is not dirty
3/8/2020   4:16 | DEBUG | SHOWQUEUE-FORCE-UPDATE | 328724: The absolute number for S02E13   is: 35
3/8/2020 4:16 | DEBUG | SHOWQUEUE-FORCE-UPDATE | Not   touching status [ Skipped ] It could be skipped/ignored/snatched/archived
3/8/2020   4:16 | DEBUG | SHOWQUEUE-FORCE-UPDATE | 328724: Not creating SQL queue - record   is not dirty
3/8/2020 4:16 | DEBUG | SHOWQUEUE-FORCE-UPDATE | 328724:   The absolute number for S02E14 is: 36
3/8/2020   4:16 | DEBUG | SHOWQUEUE-FORCE-UPDATE | Not touching status [ Skipped ] It could   be skipped/ignored/snatched/archived
3/8/2020 4:16 | DEBUG | SHOWQUEUE-FORCE-UPDATE | 328724:   Not creating SQL queue - record is not dirty
3/8/2020   4:16 | DEBUG | SHOWQUEUE-FORCE-UPDATE | 328724: The absolute number for S02E15   is: 37
3/8/2020 4:16 | DEBUG | SHOWQUEUE-FORCE-UPDATE | Not   touching status [ Archived (720p HDTV) ] It could be   skipped/ignored/snatched/archived
3/8/2020   4:16 | DEBUG | SHOWQUEUE-FORCE-UPDATE | 328724: Not creating SQL queue - record   is not dirty
3/8/2020 4:16 | DEBUG | SHOWQUEUE-FORCE-UPDATE | 328724:   The absolute number for S02E16 is: 38
3/8/2020   4:16 | DEBUG | SHOWQUEUE-FORCE-UPDATE | Not touching status [ Archived (720p   HDTV) ] It could be skipped/ignored/snatched/archived
3/8/2020 4:16 | DEBUG | SHOWQUEUE-FORCE-UPDATE | 328724:   Not creating SQL queue - record is not dirty
3/8/2020   4:16 | DEBUG | SHOWQUEUE-FORCE-UPDATE | 328724: The absolute number for S02E17   is: 39
3/8/2020 4:16 | DEBUG | SHOWQUEUE-FORCE-UPDATE | Not   touching status [ Archived (720p HDTV) ] It could be   skipped/ignored/snatched/archived
3/8/2020   4:16 | DEBUG | SHOWQUEUE-FORCE-UPDATE | 328724: Not creating SQL queue - record   is not dirty
3/8/2020 4:16 | DEBUG | SHOWQUEUE-FORCE-UPDATE | 328724:   The absolute number for S02E18 is: 40
3/8/2020   4:16 | DEBUG | SHOWQUEUE-FORCE-UPDATE | Not touching status [ Archived (720p   HDTV) ] It could be skipped/ignored/snatched/archived
3/8/2020 4:16 | DEBUG | SHOWQUEUE-FORCE-UPDATE | 328724:   Not creating SQL queue - record is not dirty
3/8/2020   4:16 | DEBUG | SHOWQUEUE-FORCE-UPDATE | 328724: The absolute number for S02E19   is: 41
3/8/2020 4:16 | DEBUG | SHOWQUEUE-FORCE-UPDATE | Not   touching status [ Archived (720p WEB-DL) ] It could be   skipped/ignored/snatched/archived
3/8/2020   4:16 | DEBUG | SHOWQUEUE-FORCE-UPDATE | 328724: The absolute number for S02E20   is: 42
3/8/2020 4:16 | DEBUG | SHOWQUEUE-FORCE-UPDATE | Not   touching status [ Archived (720p HDTV) ] It could be   skipped/ignored/snatched/archived
3/8/2020   4:16 | DEBUG | SHOWQUEUE-FORCE-UPDATE | 328724: Not creating SQL queue - record   is not dirty
3/8/2020 4:16 | DEBUG | SHOWQUEUE-FORCE-UPDATE | 328724:   The absolute number for S02E21 is: 43
3/8/2020   4:16 | DEBUG | SHOWQUEUE-FORCE-UPDATE | Not touching status [ Archived (720p   HDTV) ] It could be skipped/ignored/snatched/archived
3/8/2020 4:16 | DEBUG | SHOWQUEUE-FORCE-UPDATE | 328724:   The absolute number for S02E22 is: 44
3/8/2020   4:16 | DEBUG | SHOWQUEUE-FORCE-UPDATE | Not touching status [ Archived (720p   HDTV) ] It could be skipped/ignored/snatched/archived
3/8/2020 4:16 | DEBUG | SHOWQUEUE-FORCE-UPDATE | 328724:   Not creating SQL queue - record is not dirty
3/8/2020   4:16 | DEBUG | SHOWQUEUE-FORCE-UPDATE | 328724: The absolute number for S03E01   is: 45
3/8/2020 4:16 | DEBUG | SHOWQUEUE-FORCE-UPDATE | Not   touching status [ Archived (720p HDTV) ] It could be   skipped/ignored/snatched/archived
3/8/2020   4:16 | DEBUG | SHOWQUEUE-FORCE-UPDATE | 328724: Not creating SQL queue - record   is not dirty
3/8/2020 4:16 | DEBUG | SHOWQUEUE-FORCE-UPDATE | 328724:   The absolute number for S03E02 is: 46
3/8/2020   4:16 | DEBUG | SHOWQUEUE-FORCE-UPDATE | Not touching status [ Archived (720p   HDTV) ] It could be skipped/ignored/snatched/archived
3/8/2020 4:16 | DEBUG | SHOWQUEUE-FORCE-UPDATE | 328724:   Not creating SQL queue - record is not dirty
3/8/2020   4:16 | DEBUG | SHOWQUEUE-FORCE-UPDATE | 328724: The absolute number for S03E03   is: 47
3/8/2020 4:16 | DEBUG | SHOWQUEUE-FORCE-UPDATE | Not   touching status [ Archived (720p HDTV) ] It could be   skipped/ignored/snatched/archived
3/8/2020   4:16 | DEBUG | SHOWQUEUE-FORCE-UPDATE | 328724: Not creating SQL queue - record   is not dirty
3/8/2020 4:16 | DEBUG | SHOWQUEUE-FORCE-UPDATE | 328724:   The absolute number for S03E04 is: 48
3/8/2020   4:16 | DEBUG | SHOWQUEUE-FORCE-UPDATE | Not touching status [ Archived (720p   HDTV) ] It could be skipped/ignored/snatched/archived
3/8/2020 4:16 | DEBUG | SHOWQUEUE-FORCE-UPDATE | 328724:   Not creating SQL queue - record is not dirty
3/8/2020   4:16 | DEBUG | SHOWQUEUE-FORCE-UPDATE | 328724: The absolute number for S03E05   is: 49
3/8/2020 4:16 | DEBUG | SHOWQUEUE-FORCE-UPDATE | Not   touching status [ Archived (720p HDTV) ] It could be   skipped/ignored/snatched/archived
3/8/2020   4:16 | DEBUG | SHOWQUEUE-FORCE-UPDATE | 328724: Not creating SQL queue - record   is not dirty
3/8/2020 4:16 | DEBUG | SHOWQUEUE-FORCE-UPDATE | 328724:   The absolute number for S03E06 is: 50
3/8/2020   4:16 | DEBUG | SHOWQUEUE-FORCE-UPDATE | Not touching status [ Archived (720p   HDTV) ] It could be skipped/ignored/snatched/archived
3/8/2020 4:16 | DEBUG | SHOWQUEUE-FORCE-UPDATE | 328724:   Not creating SQL queue - record is not dirty
3/8/2020   4:16 | DEBUG | SHOWQUEUE-FORCE-UPDATE | 328724: The absolute number for S03E07   is: 51
3/8/2020 4:16 | DEBUG | SHOWQUEUE-FORCE-UPDATE | 328724:   Setting status for S03E07 based on status Downloaded (SDTV) and location   /tv/Young Sheldon/S03E07/Pongo Pygmaeus and a Culture that Encourages   Spitting SDTV.mkv
3/8/2020   4:16 | DEBUG | SHOWQUEUE-FORCE-UPDATE | Not touching status [ Downloaded (SDTV)   ] It could be skipped/ignored/snatched/archived
3/8/2020 4:16 | DEBUG | SHOWQUEUE-FORCE-UPDATE | 328724:   Not creating SQL queue - record is not dirty
3/8/2020 4:20 | DEBUG | SEARCHQUEUE-DAILY-SEARCH :: Seeing   if we need anything from Young Sheldon
```

**Comment by ronrosenfeld** [comment]
@miigotu  I know you've said to *"let it run"* and that *"Unless the log shows something, there is nothing to do."*, 

but:

 - Letting it run, even for a few days, doesn't clear it, or even show progression
 - When in the **stuck** state, the post-processing script being run from `nzbGet`  (`nzbMedia`) will time out (about 30 minutes) before it gets any acknowledgement from Sickchill that the script ran successfully, so `nzbGet` will show an error, even if the post-process has completed in SickChill, which it usually has.

The only workaround I have is to restart Sickchill.
Any other thoughts?
Thanks.

**Comment by miigotu** [comment]
running out of memory or disk space? I cannot reproduce this problem, you will need to find a way to figure out what's failing on your end.

**Comment by ronrosenfeld** [comment]
Never thought of memory since other services didn't seem to slow down.  But I'll check the utilization the next time there's an issue.  The DS718+ came with 2GB RAM, but could be upgraded to 6GB.  Definitely not diskspace with >2TB free.  And nothing in the log suggesting a TVDB failure.

Thanks.

Ron

**Comment by miigotu** [comment]
I remember something about a setting in nzbtomedia that was freezing SC for others. Did you try to set the fork to auto in nzbtomedia config?

Also, I did not know that you were on a Synology. Next time, put that along with your info because that system has some caveats. What spk package are you using?

**Comment by ronrosenfeld** [comment]
I do have  `sbfork` set to **auto** in nzbtomedia config.

And in my first post on this thread, I have:

`OS: Docker on Synology NAS`

Is there someplace else I should have that information?

So far as Docker vs spk, when I first upgraded to my current Synology NAS, I was unable to find current spk's for the two programs.  So I installed Docker (provided by Synology), and it's seemed to work OK, with the caveats about not being to update from within the application with the container from Linuxserver.

**Comment by miigotu** [comment]
Benjv has a spk for it, and I'm working on an official sickchill spk but I need to fix a small issue with it before it's ready.

**Comment by miigotu** [comment]
I suspect your issue is related to running it in docker on syno and that extra overhead causing memory/CPU spikes.

**Comment by ronrosenfeld** [comment]
I'll try adding memory as a next step. It has 2GB and can be expanded to 6GB.

**Comment by ronrosenfeld** [comment]
No joy.,

I added memory to the maximum capacity (6GB) and also set alarms for memory or CPU use over 80%.
No alarms triggered and this morning the Queue stuck again.

Examining the logs I see multiple errors like this:

```
2020-06-27 03:31:16 DEBUG    SHOWQUEUE-FORCE-UPDATE :: 295647: Creating episode object from /tv/Blindspot/S04E14/The Big Blast from the Past Episode 720p HDTV x264.mkv
2020-06-27 03:31:16 DEBUG    SHOWQUEUE-FORCE-UPDATE :: Trying to find [u'the big blast from the past'] on theTVDB
2020-06-27 03:31:16 DEBUG    SHOWQUEUE-FORCE-UPDATE :: Error when attempting to find show: The Big Blast from the Past in SickChill. Error: expected string or buffer 
2020-06-27 03:31:16 DEBUG    SHOWQUEUE-FORCE-UPDATE :: Traceback (most recent call last):
  File "/app/sickchill/sickbeard/helpers.py", line 1046, in get_show
    sickbeard.showList, sickchill.indexer.search_indexers_for_series_id(name=full_sanitizeSceneName(name))[1].id)
  File "/app/sickchill/sickchill/show/indexers/handler.py", line 137, in search_indexers_for_series_id
    result = self.indexers[i].get_series_by_name(n, indexerid, language)
  File "/app/sickchill/sickchill/show/indexers/tvdb.py", line 87, in get_series_by_name
    result = self._series(self.search(name, language)[0]['id'])
  File "/app/sickchill/sickchill/show/indexers/wrappers.py", line 44, in wrapper
    result = target(*args, **kwargs)
  File "/app/sickchill/sickchill/show/indexers/tvdb.py", line 143, in search
    test = re.match(r'^(.+?)[. -]+\(\d{4}\)?$', name)
  File "/usr/lib/python2.7/re.py", line 141, in match
    return _compile(pattern, flags).match(string)
TypeError: expected string or buffer

2020-06-27 03:31:16 DEBUG    SHOWQUEUE-FORCE-UPDATE :: Parsed /tv/Blindspot/S04E14/The Big Blast from the Past Episode 720p HDTV x264.mkv into The Big Blast from the Past - S04E720 [ABD: False] [ANIME: False] [whichReg: [u'no_season_general', u'standard']]
2020-06-27 03:31:16 DEBUG    SHOWQUEUE-FORCE-UPDATE :: 295647: /tv/Blindspot/S04E14/The Big Blast from the Past Episode 720p HDTV x264.mkv parsed to Blindspot S04E720
```


But they don't seem to relate to the issue, since I have seen this on other days when the queue did not get stuck.

If you have time, maybe the full log, starting a few minutes before the entries were made into the Show Queue will be of more value?  I also included a screenshot of the stuck Queue.  

And I have several more days of debug logs if you think they might be of any value.

Thanks.

Ron

[Sickchill 20200627.zip](https://github.com/SickChill/SickChill/files/4840593/Sickchill.20200627.zip)

**Comment by miigotu** [comment]
This is fixed in the develop branch (Python3.6+ only)

**Comment by ronrosenfeld** [comment]
Thanks! I guess that means you found the cause. 
I've been running under Docker using the Linuxserver container and they don't have the develop branch yet.  Hopefully soon.
In the meantime, I've been restarting Sickchill every morning (cron job on synology) as a workaround.

**Comment by ronrosenfeld** [comment]
@miigotu Nope. Not fixed.  `<sigh>`
For at least the past hour, has been stuck on "Force Update" for the same show.
And checking the Synology NAS resource monitor, there have been no spikes in CPU or memory usage (and average usage has been fairly low -- around 11% for memory and lower for CPU.

**Comment by miigotu** [comment]
look at the debug log and see where it is stuck. check the log file itself not the gui

**Comment by ronrosenfeld** [comment]
I'd been out of town, but I finally have a relevant debug log file, which I have zipped and attached.

The frozen Server Queue occurred this morning, and seems to be related to line` 30,341` in the log. `2020-10-22 03:40:01`
I really can't tell a reason from the log; I included more than just today so as to include an event sequence (from 21-Oct) that completed successfully.

Thank you for any help.

[sickchillLog.zip](https://github.com/SickChill/SickChill/files/5422553/sickchillLog.zip)

![Show Queue Screenshot 2020-10-22 073540](https://user-images.githubusercontent.com/18516066/96869443-74331f00-143d-11eb-9f04-c24553e10267.png)

**Comment by ronrosenfeld** [comment]
If anyone else happens across this thread, I may have found and solved the problem.
My interim fix was to set a cron task (or Task Scheduler) to restart the Sickchill docker container every morning.

But about two weeks ago, due to some other issues, I removed the "Bond" I had set up between my two Synology ports.  (This had been enabled to obtain faster throughput on the LAN).

Since removing the Bond, (and also the scheduled daily restart of Sickchill), the problem has not recurred.  Synology support stated that the Bond could cause problems with Docker as well as some other issues I had been experiencing.

**Comment by nydave69** [comment]
I have seen this problem for months,  I reported it a while back it got closed..

SickChill Configuration
  SickChill Info:
Install: pip
Version: v2021.11.10
Database Version: 44.5
  Python Version:3.8.10 (tags/v3.8.10:3d8993a, May 3 2021, 11:48:03) [MSC v.1928 64 bit (AMD64)]
  SSL Version:OpenSSL 1.1.1k 25 Mar 2021
  OS:Windows-7-6.1.7601-SP1
  Locale:en_US.cp1252

It happens every day,  If I do nothing there are hundreds in the queue a lot of duplicated..
Restart of SC is only way to clear it..  I have to do that each morning because SC does a scan overnight filling it.

![image](https://user-images.githubusercontent.com/14140816/146955483-a7e77184-35de-4ace-8c3e-9bab2df1c47c.png)

It happens even if SC is the only process running..

**Comment by ronrosenfeld** [comment]
@nydave69 Wow, another sufferer.  I reported my issue almost two years ago. I thought it might be something specific to the Docker on Synology OS, but I see you are running Windows.  I confess I've not seen hundreds, nor duplicates.  And, like you, my only fix has been to restart Sickchill every day.  I do this using a cron job (task scheduler) on the Synology NAS.  

I have another setup where Sickchill is running on windows (windows 10 prof)  as a service, and I have NOT seen this problem there.  Maybe, someday, there will be enough data so the problem can be solved.

**Comment by nydave69** [comment]
> I have another setup where Sickchill is running on windows (windows 10 prof) as a service, and I have NOT seen this problem there. Maybe, someday, there will be enough data so the problem can be solved.

Yeah,  and the will to fix it.
So what I have figured out it seems to hang for a very long time while it trying to get something from an online DB..
not a programmer here..  just what i can figure out on my own..

**Comment by Telecart** [comment]
Same issue I think, I have a show with the “ This show is queued and awaiting an update.” that never clears up for at least like a week now. Running pip install on a Mac.
