### ISSUE TITLE
SickChill/Python3 not respecting language preferences

### ISSUE THREAD

**Issue by osasco** [SickChill/SickChill#6773]
Branch/Commit: c9a015b4b90ef673c57a79dc600e3fa183576013
OS: Linux - Debian Buster - The system locale is pt_BR.UTF-8
Browser: Chrome
What you did: selected "English (US)" in General / Interface / Interface language
![English](https://user-images.githubusercontent.com/40818544/93535356-2b0f1d00-f91d-11ea-8e00-a18f97159005.JPG)

What happened: Some parts of the web interface are in Portuguese (Brazil), the system locale.
![Portuguese](https://user-images.githubusercontent.com/40818544/93535365-306c6780-f91d-11ea-85d6-bc1348a62c90.jpg)

What you expected: Everything in English, as it was when using Python 2.

**Comment by miigotu** [comment]
Cannot reproduce. Make sure you are refreshing the page with a hard refresh. You might need to restart the service for some things that are set in javascript.

**Comment by osasco** [comment]
@miigotu , hello.

This is not a cache issue.

After the Python3 change (or some code in this release) that list is being rendered based on the system locale that SickChill is running on. It ignores the user language selection. 

More examples:

1) I've changed the system locale to German and rebooted the server:
![02 - Alterar locale para DE](https://user-images.githubusercontent.com/40818544/93612819-5f7aeb80-f9a6-11ea-9e96-f70ff38c1c21.JPG)

2) The list (just the list) is now in German:
![03 - Ficou em Alemão](https://user-images.githubusercontent.com/40818544/93612864-73bee880-f9a6-11ea-84bc-fd4fefd5fa03.JPG)

3) I've changed the system locale to Japanese and rebooted the server:
![04 - Alterar locale para JP](https://user-images.githubusercontent.com/40818544/93612891-81746e00-f9a6-11ea-9d86-7d41a270d666.JPG)

4) The list is now in Japanese:
![05 - Interface em JP](https://user-images.githubusercontent.com/40818544/93612914-89341280-f9a6-11ea-8b7d-29d06e92b956.JPG)


Just to be clear, SickChill is running on a Debian machine and I'm browsing on a Windows PC. It wasn't necessary to clear the cache between any of these steps.

**Comment by osasco** [comment]
@miigotu , can you please reopen this issue?

Problem persists in commit 79a5a4a7cddf021bfd4a458eef256818ff39288d.

**Comment by miigotu** [comment]
Sir, this is an Arby's.

**Comment by miigotu** [comment]
Might have been your browser caching the data. Hopefully it is now fixed.

**Comment by osasco** [comment]
I'm running commit: a1024f1ffaf7d4261929f71977a745134cd0ec5a

I can confirm that it is not fixed. As I've previously shown, https://github.com/SickChill/SickChill/issues/6773#issuecomment-694924454, changing **just** the server locale and rebooting **just** the server, changed the _episode status_ language. That's why it isn't a cache issue. I haven't closed the browser between these captures. Just an F5 after each reset was sufficient to change the _episode status_ language.

I don't know if you use Debian. Maybe it's something that happens because of a Debian-Python internationalization integration and it might not happen in other distributions.
