### ISSUE TITLE
Recent update failed

### ISSUE THREAD

**Issue by zerosaber071** [SickChill/SickChill#7177]
Good day,
I tried to the latest commit and received the following:

Traceback (most recent call last):
  File "/opt/sickchill/SickChill.py", line 14, in <module>
    import sickchill.start
  File "/opt/sickchill/sickchill/__init__.py", line 1, in <module>
    from .show.indexers import indexer, ShowIndexer
  File "/opt/sickchill/sickchill/show/indexers/__init__.py", line 1, in <module>
    from .handler import ShowIndexer
  File "/opt/sickchill/sickchill/show/indexers/handler.py", line 5, in <module>
    from sickchill.tv import Show, TVEpisode
  File "/opt/sickchill/sickchill/tv.py", line 19, in <module>
    import sickchill.oldbeard.providers
  File "/opt/sickchill/sickchill/oldbeard/providers/__init__.py", line 6, in <module>
    from sickchill.oldbeard.providers import (
  File "/opt/sickchill/sickchill/oldbeard/providers/abnormal.py", line 8, in <module>
    from sickchill.oldbeard import tvcache
  File "/opt/sickchill/sickchill/oldbeard/tvcache.py", line 10, in <module>
    from . import db, show_name_helpers
  File "/opt/sickchill/sickchill/oldbeard/show_name_helpers.py", line 10, in <module>
    from .name_parser.parser import InvalidNameException, InvalidShowException, NameParser
  File "/opt/sickchill/sickchill/oldbeard/name_parser/parser.py", line 23, in <module>
    class NameParser(object):
  File "/opt/sickchill/sickchill/oldbeard/name_parser/parser.py", line 28, in NameParser
    def __init__(self, filename: bool = True, showObj: TVShow = None, tryIndexers: bool = False, namin
g_pattern: bool = False, parse_method: str = None):
NameError: name 'TVShow' is not defined

**Comment by Xx-Ness-xX** [comment]
Hello,

I am having the exact same issue after the ed50be8 commit:
OS: Windows 10

Traceback (most recent call last):
  File "D:\SickChill\SickChill.py", line 14, in <module>
    import sickchill.start
  File "D:\SickChill\sickchill\__init__.py", line 1, in <module>
    from .show.indexers import indexer, ShowIndexer
  File "D:\SickChill\sickchill\show\indexers\__init__.py", line 1, in <module>
    from .handler import ShowIndexer
  File "D:\SickChill\sickchill\show\indexers\handler.py", line 5, in <module>
    from sickchill.tv import Show, TVEpisode
  File "D:\SickChill\sickchill\tv.py", line 19, in <module>
    import sickchill.oldbeard.providers
  File "D:\SickChill\sickchill\oldbeard\providers\__init__.py", line 6, in <module>
    from sickchill.oldbeard.providers import (
  File "D:\SickChill\sickchill\oldbeard\providers\abnormal.py", line 8, in <module>
    from sickchill.oldbeard import tvcache
  File "D:\SickChill\sickchill\oldbeard\tvcache.py", line 10, in <module>
    from . import db, show_name_helpers
  File "D:\SickChill\sickchill\oldbeard\show_name_helpers.py", line 10, in <module>
    from .name_parser.parser import InvalidNameException, InvalidShowException, NameParser
  File "D:\SickChill\sickchill\oldbeard\name_parser\parser.py", line 23, in <module>
    class NameParser(object):
  File "D:\SickChill\sickchill\oldbeard\name_parser\parser.py", line 28, in NameParser
    def __init__(self, filename: bool = True, showObj: TVShow = None, tryIndexers: bool = False, naming_pattern: bool = False, parse_method: str = None):
NameError: name 'TVShow' is not defined

**Comment by pejub** [comment]
I have this issue too, Ubuntu 20.04 commit ed50be8.

/usr/bin/python3.8 /opt/sickrage/SickChill.py -q --daemon --nolaunch --datadir=/opt/sickrage
/opt/sickrage/sickchill/locale
/opt/sickrage/sickchill/locale
Traceback (most recent call last):
  File "/opt/sickrage/SickChill.py", line 14, in <module>
    import sickchill.start
  File "/opt/sickrage/sickchill/__init__.py", line 1, in <module>
    from .show.indexers import indexer, ShowIndexer
  File "/opt/sickrage/sickchill/show/indexers/__init__.py", line 1, in <module>
    from .handler import ShowIndexer
  File "/opt/sickrage/sickchill/show/indexers/handler.py", line 5, in <module>
    from sickchill.tv import Show, TVEpisode
  File "/opt/sickrage/sickchill/tv.py", line 19, in <module>
    import sickchill.oldbeard.providers
  File "/opt/sickrage/sickchill/oldbeard/providers/__init__.py", line 6, in <module>
    from sickchill.oldbeard.providers import (
  File "/opt/sickrage/sickchill/oldbeard/providers/abnormal.py", line 8, in <module>
    from sickchill.oldbeard import tvcache
  File "/opt/sickrage/sickchill/oldbeard/tvcache.py", line 10, in <module>
    from . import db, show_name_helpers
  File "/opt/sickrage/sickchill/oldbeard/show_name_helpers.py", line 10, in <module>
    from .name_parser.parser import InvalidNameException, InvalidShowException, NameParser
  File "/opt/sickrage/sickchill/oldbeard/name_parser/parser.py", line 23, in <module>
    class NameParser(object):
  File "/opt/sickrage/sickchill/oldbeard/name_parser/parser.py", line 28, in NameParser
    def __init__(self, filename: bool = True, showObj: TVShow = None, tryIndexers: bool = False, naming_pattern: bool = False, parse_method: str = None):
NameError: name 'TVShow' is not defined

**Comment by rovaals** [comment]
Same exact error on Ubuntu 20.04

**Comment by kyuuk** [comment]
Little workaround while waiting for a fix :
you could edit the file sickchill/oldbeard/name_parser/parser.py and change lines 28 & 31

from this 
```
    def __init__(self, filename: bool = True, showObj: TVShow = None, tryIndexers: bool = False, naming_pattern: bool = False, parse_method: str = None):

        self.filename: bool = filename
        self.showObj: TVShow = showObj
```
to this 

```
    def __init__(self, filename: bool = True, showObj = None, tryIndexers: bool = False, naming_pattern: bool = False, parse_method: str = None):

        self.filename: bool = filename
        self.showObj = showObj
```
Notice the  `: TVShow` was deleted

**Comment by ediazrod** [comment]
Happens to me too, thanks for the update..

**Comment by bink999999** [comment]
Yeah, that did not work.

**Comment by bink999999** [comment]
Reinstalled clean 3 times. Software will not load. Totally broken.

**Comment by snapperhead** [comment]
> Little workaround while waiting for a fix :
> you could edit the file `sickchill/oldbeard/name_parser/parser.py` and change lines 28 & 31
> 
> from this
> 
> ```
>     def __init__(self, filename: bool = True, showObj: TVShow = None, tryIndexers: bool = False, naming_pattern: bool = False, parse_method: str = None):
> 
>         self.filename: bool = filename
>         self.showObj: TVShow = showObj
> ```
> 
> to this
> 
> ```
>     def __init__(self, filename: bool = True, showObj = None, tryIndexers: bool = False, naming_pattern: bool = False, parse_method: str = None):
> 
>         self.filename: bool = filename
>         self.showObj = showObj
> ```
> 
> Notice the `: TVShow` was deleted

This 100% fixed issue with windows 10.

**Comment by TheExpertNoob** [comment]
> Little workaround while waiting for a fix :
> you could edit the file `sickchill/oldbeard/name_parser/parser.py` and change lines 28 & 31
> 
> from this
> 
> ```
>     def __init__(self, filename: bool = True, showObj: TVShow = None, tryIndexers: bool = False, naming_pattern: bool = False, parse_method: str = None):
> 
>         self.filename: bool = filename
>         self.showObj: TVShow = showObj
> ```
> 
> to this
> 
> ```
>     def __init__(self, filename: bool = True, showObj = None, tryIndexers: bool = False, naming_pattern: bool = False, parse_method: str = None):
> 
>         self.filename: bool = filename
>         self.showObj = showObj
> ```
> 
> Notice the `: TVShow` was deleted

This method worked for me in Linux.

...
sudo service sickchill restart
...

to bring sickchill back up after the edit.

**Comment by bjwest** [comment]
Author of #7179 here.  The workaround worked for me as well on Linux.  Thank you @snapperhead.

**Comment by bink999999** [comment]
Worked after restart and restore. Had to manually apply recent library updates.

**Comment by prophead67** [comment]
Similar errors, fix also worked for me in Ubuntu 20.04. Started the service and voila, there was a new update to apply. Autostarted without intervention.
Thanks @kyuuk

**Comment by graeme86** [comment]
Fixed worked for me on freenas as well.

**Comment by PluX-0** [comment]
Sadly this fix did not work for me on my synology. See #7180

**Comment by Wally73** [comment]
after the hotfix (show fix) it still doesn't work on windows 10 
Python 3.8.6

`G:\SR1>python SickChill.py
Traceback (most recent call last):
  File "SickChill.py", line 14, in <module>
    import sickchill.start
  File "G:\SR1\sickchill\__init__.py", line 1, in <module>
    from .show.indexers import indexer, ShowIndexer
  File "G:\SR1\sickchill\show\indexers\__init__.py", line 1, in <module>
    from .handler import ShowIndexer
  File "G:\SR1\sickchill\show\indexers\handler.py", line 3, in <module>
    from sickchill import logger, settings
  File "G:\SR1\sickchill\logger.py", line 16, in <module>
    from github import InputFileContent
  File "G:\SR1\lib3\github\__init__.py", line 56, in <module>
    from github.MainClass import Github, GithubIntegration
  File "G:\SR1\lib3\github\MainClass.py", line 59, in <module>
    import github.Event
  File "G:\SR1\lib3\github\Event.py", line 32, in <module>
    import github.NamedUser
  File "G:\SR1\lib3\github\NamedUser.py", line 44, in <module>
    import github.Organization
  File "G:\SR1\lib3\github\Organization.py", line 50, in <module>
    import github.Repository
  File "G:\SR1\lib3\github\Repository.py", line 125, in <module>
    import github.PublicKey
  File "G:\SR1\lib3\github\PublicKey.py", line 34, in <module>
    from nacl import encoding, public
  File "G:\SR1\lib3\nacl\public.py", line 17, in <module>
    import nacl.bindings
  File "G:\SR1\lib3\nacl\bindings\__init__.py", line 17, in <module>
    from nacl.bindings.crypto_aead import (
  File "G:\SR1\lib3\nacl\bindings\crypto_aead.py", line 18, in <module>
    from nacl._sodium import ffi, lib
ModuleNotFoundError: No module named 'nacl._sodium'

G:\SR1>`

**Comment by BKSteve** [comment]
`ModuleNotFoundError: No module named 'nacl._sodium'`
looks like a develop branch issue.

**Comment by Wally73** [comment]
> `ModuleNotFoundError: No module named 'nacl._sodium'`
> looks like a develop branch issue.

Yes its in develop

**Comment by kyuuk** [comment]
Hello all, as the fix was released you should all update to commit 94f56b7e2c86655fc98d93e94be1a75e729d3969

**Comment by turkeylegs1** [comment]
How can I update it when it is not a git project (ran a few git commands,
but the reported message is consistently "this is not a git project and
there are none found up to the base director. ")
It's a Synology NAS that is looking for .spk files for installation. I
*can* drop the entire thing and recreate from backup after doing a git pull
or fetch or whatever, or maybe pull from docker. I'm not sure what is best
here.
