### ISSUE TITLE
No Longer Able Unable to Connect To BTN - SSLCertVerificationError

### ISSUE THREAD

**Issue by davidlinke** [SickChill/SickChill#7311]
Branch/Commit: e1e91c3ec3c90479b556e7e78b48dc3bb81ead01
OS: macOS 10.15.7

After updating a few days ago I keep getting an error when trying to search BTN. I did a preliminary search on BTN on this issue and found an old forum post saying this is likely a client side issue rather than an issue on their end.

Logs:
```
17:41:27 ERROR :: SEARCHQUEUE-MANUAL-79264 :: [BTN] :: Exception while searching BTN. Error: 'SSLCertVerificationError' object is not subscriptable 2021-07-16 17:41:27 INFO :: SEARCHQUEUE-MANUAL-79264 :: [BTN] :: Performing episode search for Grand Designs AA TypeError: 'SSLCertVerificationError' object is not subscriptable AA logger.warning("Socket error while accessing provider. Error: {0} ".format(error[1])) AA File "/Applications/SickChill/sickchill/oldbeard/providers/btn.py", line 134, in _api_call AA parsed_json = self._api_call(apikey, params) AA File "/Applications/SickChill/sickchill/oldbeard/providers/btn.py", line 68, in search AA return {"entries": self.provider.search(search_params=self.search_params, age=seconds_since_last_update)} AA File "/Applications/SickChill/sickchill/oldbeard/providers/btn.py", line 288, in _get_rss_data AA data = self._get_rss_data() AA File "/Applications/SickChill/sickchill/oldbeard/tvcache.py", line 66, in update_cache AA Traceback (most recent call last): AA During handling of the above exception, another exception occurred: AA ssl.SSLCertVerificationError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1123) AA self._sslobj.do_handshake() AA File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/ssl.py", line 1309, in do_handshake AA self.do_handshake() AA File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/ssl.py", line 1040, in _create AA return self.sslsocket_class._create( AA File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/ssl.py", line 500, in wrap_socket AA self.sock = self._context.wrap_socket(self.sock, AA File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/http/client.py", line 1424, in connect AA self.connect() AA File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/http/client.py", line 950, in send AA self.send(msg) AA File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/http/client.py", line 1010, in _send_output AA self._send_output(message_body, encode_chunked=encode_chunked) AA File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/http/client.py", line 1250, in endheaders AA connection.endheaders() AA File "/Applications/SickChill/.venv/lib/python3.9/site-packages/jsonrpclib/jsonrpc.py", line 476, in send_content AA self.send_content(connection, request_body) AA File "/Applications/SickChill/.venv/lib/python3.9/site-packages/jsonrpclib/jsonrpc.py", line 413, in single_request AA return self.single_request(host, handler, request_body, verbose) AA File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/xmlrpc/client.py", line 1160, in request AA response = self.__transport.request( AA File "/Applications/SickChill/.venv/lib/python3.9/site-packages/jsonrpclib/jsonrpc.py", line 730, in _run_request AA response = self._run_request(request) AA File "/Applications/SickChill/.venv/lib/python3.9/site-packages/jsonrpclib/jsonrpc.py", line 695, in _request AA return self.__send(self.__name, args) AA File "/Applications/SickChill/.venv/lib/python3.9/site-packages/jsonrpclib/jsonrpc.py", line 821, in __call__ AA parsed_json = server.getTorrents(apikey, params or {}, int(results_per_page), int(offset)) AA File "/Applications/SickChill/sickchill/oldbeard/providers/btn.py", line 116, in _api_call 2021-07-16 
```

**Comment by miigotu** [comment]
This should have been fixed on the 16th, their certificate was expired, and was renewed `Friday, July 16, 2021 at 8:00:00 PM` which means depending on the time zone could be +/- a day

**Comment by davidlinke** [comment]
@miigotu I am still experiencing this issue today. Is there a cache I need to clear or something?

Thanks for your help!

**Comment by miigotu** [comment]
I'll try and look some more at the code, but I don't have an account there

**Comment by davidlinke** [comment]
Thanks, if there's any additional logging or debugging steps I can take to help diagnose it let me know.
